### ISSUE TITLE
BaseItemTypes.IsPickedUpByMonsters might be misidentified

### ISSUE THREAD

**Issue by duskwuff** [OmegaK2/PyPoE#104]
The [`BaseItemTypes.IsPickedUpByMonsters`](https://github.com/OmegaK2/PyPoE/blob/25737ddc7b9aa34589626094102b5d9e4682f7f0/PyPoE/poe/file/specification/data/stable.py#L2034) field isn't just true for talismans -- it's also true for `Metadata/Items/Rings/BreachRing` and leaguestones. Based on this, I suspect it actually means "always corrupted".

**Comment by OmegaK2** [comment]
I see, I'll change it to IsCorrupted
