### ISSUE TITLE
pyside not supported on python 3.5 (windows)

### ISSUE THREAD

**Issue by ColinDabritz** [OmegaK2/PyPoE#11]
I'm running on Windows 7, with a python 3.5 install, running out of Visual Studio 2015 RC2

I was able to get pip to run the install script.
In case this comes up again, in visual studio, if you select the python environment in the environments viewer, then choose the 'pip' subtab, you can directly enter install commands in the search. It then comes up with a result to execute the install. I had to take the local path '.' and fully qualify it, so I was executing from a link below a search for esentially:
`-e C:\SomeFolders\GitHubVisualStudio\PyPoE[full]`

This seemed to work well, but it broke with the following log:

```
----- Installing '-e C:\Users\Colin\Documents\GitHubVisualStudio\PyPoE[full]' -----
Obtaining file:///C:/Users/Colin/Documents/GitHubVisualStudio/PyPoE
Collecting configobj (from PyPoE==1.0.0a0)
  Downloading configobj-5.0.6.tar.gz
Collecting PySide (from PyPoE==1.0.0a0)
  Downloading PySide-1.2.4.tar.gz (9.3MB)
    Complete output from command python setup.py egg_info:
    only these python versions are supported: [(2, 6), (2, 7), (3, 2), (3, 3), (3, 4)]

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Colin\AppData\Local\Temp\pip-build-d0d108fz\PySide
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
----- Failed to install '-e C:\Users\Colin\Documents\GitHubVisualStudio\PyPoE[full]' -----
```

It seems pretty clear that it's pulling a version of PySide that only supports python 3.4.

I'm not sure if this is expected behavior, or if there is a work-around, perhaps I missed something during the process. I also tried installing PySide from the pip search and got the same version of PySide with the same error.

As a work-around, I'm installing a Python 3.4 environment.

If this is an issue specifically with my windows-visualstudio setup, I can troubleshoot further, otherwise perhaps PySide is holding the project back at 3.4? If it is a problem I can address, I am happy to do so, but I do not know what the current state is intended to be, so I figured I would post the information I had and check in before bumbling around in your codebase.

Thanks for the excellent codebase to explore.

**Comment by ColinDabritz** [comment]
The non-full install appears to have worked, and I'm continuing to work from there. Are the requirements for the 'Full' install different?

**Comment by OmegaK2** [comment]
The full install install all the extensions installs all 3rd party libraries. Pyside is needed for any UI components of pypoe which is the GGPK viewer at the point of writing. 
It's a bit of a predicament right now, pyside2 is being developed and it would support Qt5 and Python 3.5, but doesn't seem to be quite there yet. There is also PyQT5 as option which I've avoided due to being GPL licensed

**Comment by OmegaK2** [comment]
I've updated to pyside2 which will now run on newer python versions (3.5, 3.6, 3.7), though there is no version for 3.4 at the moment.
