### ISSUE TITLE
DDS decompression fails due to GGG having a loose sense of what a texture file is

### ISSUE THREAD

**Issue by AntonUklein** [OmegaK2/PyPoE#113]
**Reproduction steps**: Extract and decompress the _Art\Textures\Interface\2D\_ folder; it will fail after it hits _2DArt_UIImages_InGame_Shop_French_2.dds_ because the DDS file is a reference to an existing graphic instead.

If there's a good way to add a try/catch the process such that it skips over a file if decompression fails, that would make my life a lot easier.

**Comment by zao** [comment]
Some of the language-specific store images are symbolic links to missing files, I'd guess that they're probably not in use anymore and use the culture-neutral background art.

**Comment by OmegaK2** [comment]
I assume you're talking about the ggpk viewer and not the API as I initially thought. With the API you can just do a try ... except FileNotFoundError in that case. I'll fix this for the viewer
