### ISSUE TITLE
Recent update (6/22/2016)

### ISSUE THREAD

**Issue by Manevolent** [OmegaK2/PyPoE#12]
In data file ItemVisualIdentity.dat, I've noticed that the second column, IDTFile, has remained a string but no longer references IDT files -- it now points to DDS image files (which appear to be holding icons). I'm not sure if the IDT file column has moved elsewhere in the table since I no longer needed it in my own code (I was using it purely to find the DDS files).

**Comment by OmegaK2** [comment]
Most of the .idt files were just pointing to an .dds icon anyway. I suppose they just skipped loading the .idt file to improve performance. Anyway, changed the name to fix that
