### ISSUE TITLE
pypoe not working with new ggpk from 3.12.1 patch

### ISSUE THREAD

**Issue by markliu06** [OmegaK2/PyPoE#132]
yellow text

>  c:\users\t\documents\poewiki\pypoe\PyPoE\poe\file\ggpk.py:1037:
> UserWarning: Invalid tag b'\x06\x00\x00\x00' - seeking next valid tag

and then red text

> Traceback (most recent call last):
>   File "c:\users\t\documents\poewiki\pypoe\PyPoE\cli\handler.py", line 309, in setup
>     func(args)
>   File "c:\users\t\documents\poewiki\pypoe\PyPoE\cli\exporter\wiki\core.py", line 100, in _setup
>     ggpk['Data'].extract_to(temp_dir)
>   File "c:\users\t\documents\poewiki\pypoe\PyPoE\poe\file\ggpk.py", line 819, in __getitem__
>     return self.directory[item]
>   File "c:\users\t\documents\poewiki\pypoe\PyPoE\poe\file\ggpk.py", line 579, in __getitem__
>     raise FileNotFoundError('%s/%s not found' % (
> FileNotFoundError: /Data not found

Already remove whole pypoe installation and made a fresh install. I guess there is something wrong to unzip the subpackage inside the ggpk?

Also, would pypoe currently work for Steam? Since Steam version did not have ggpk so that can't specify ggpk location

(Also, should i delete everything "C:\Users\t\AppData\Roaming\PyPoE" for a fresh installation or it just store the setting?

**Comment by OmegaK2** [comment]
I'm still working on the wiki exporter. There is no data directory anymore since it's all contained in bundles now

**Comment by markliu06** [comment]
Resolved due to the pypoe updates.
