### ISSUE TITLE
Can't get pypoe_ui to run

### ISSUE THREAD

**Issue by drac69** [OmegaK2/PyPoE#139]
- [x] Python 3.7 64bit installed
- [x] Python & Python\Scripts are in PATH env variables

For whatever reason I can't get "pypoe_ui" to start up, I see the spinning mouse cursor after executing the command but nothing shows on the screen. I've tested this on another W7 vm incase my current installation has something fucked up, but got the same thing. Also compiled the whole ooz project and placed the "libooz.dll" inside python's folder but no change.

[Log](https://pastebin.com/cE4GFwqu) after performing "pip install -e .[full]" inside "PyPoe" folder where "setup.py" is located.

Is there another log I can provide for more information or am I lacking some critical information ??

**Comment by scottmudge** [comment]
Same issue for me.

**Comment by scottmudge** [comment]
I got it running. 

`PyPoE\ui\shared\file\handler.py` has a bug.

`from PyPoE.poe.file.ggpk import extract_dds`

should be 

`import PyPoE.poe.file.file_system as file_system`

And near line 384, 

`file_data = io.BytesIO(extract_dds(file_bytes))`

should be

`file_data = io.BytesIO(file_system.extract_dds(file_bytes))`

**Comment by markliu06** [comment]
I don't think it would work after 3.11.2 patch. OmegaK2 knew this issue.
