### ISSUE TITLE
Post 3.13 export row size error: area, map (skill, mod, monster seems fixed)

### ISSUE THREAD

**Issue by markliu06** [OmegaK2/PyPoE#143]
edit: area still not yet fixed

original issue 1 (fixed):
`PyPoE.poe.file.specification.errors.SpecificationError:<ERRORS.RUNTIME_ROWSIZE_MISMATCH: 3002>: "ActiveSkills.dat": Specification row size 114 vs real size 122`

**Comment by markliu06** [comment]
I guess mod export also went wrong (edit: seem fixed)

`PyPoE.poe.file.specification.errors.SpecificationError: <ERRORS.RUNTIME_ROWSIZE_MISMATCH: 3002>: "Mods.dat": Specification row size 338 vs real size 342`

**Comment by dayaftereh** [comment]
Also `MonsterVarieties.dat`
```
PyPoE.poe.file.specification.errors.SpecificationError: <ERRORS.RUNTIME_ROWSIZE_MISMATCH: 3002>: "MonsterVarieties.dat": Specification row size 438 vs real size 439
```

**Comment by markliu06** [comment]
the area extract also has red text too

`PyPoE.poe.file.specification.errors.SpecificationError: <ERRORS.RUNTIME_ROWSIZE_MISMATCH: 3002>: "WorldAreas.dat": Specification row size 480 vs real size 492`

**Comment by dayaftereh** [comment]
Does anyone has a fix for this ?

**Comment by markliu06** [comment]
> Does anyone has a fix for this ?

you need to wait for omegak2 online, or you edit the file yourself. I guess it is due to GGG add a few column / row to its internal file so that pypoe no longer able match the cell and extract the data

**Comment by markliu06** [comment]
Ok, after omegak2 update the pypoe.

Tried

Skill gem. seem fine (separate issue. Can't export alt quality such as "Cast on Melee Kill Support". Some are add manually by https://pathofexile.gamepedia.com/User:Latereal)

Monster: seem fine

Monster skill: seem fine (have some yellow text due to parsing some mod)

mod: seem fine

**Comment by markliu06** [comment]
Ok, checked "area"

Still have 

`PyPoE.poe.file.specification.errors.SpecificationError: <ERRORS.RUNTIME_ROWSIZE_MISMATCH: 3002>: "WorldAreas.dat": Specification row size 480 vs real size 492`

**Comment by markliu06** [comment]
Ok, discovered another rowsize error when try to export map, may be due to the new atlas passive

`PyPoE.poe.file.specification.errors.SpecificationError: <ERRORS.RUNTIME_ROWSIZE_MISMATCH: 3002>: "AtlasNode.dat": Specification row size 217 vs real size 209`

**Comment by markliu06** [comment]
Close this as it is not relevant to 3.14. 3.14 has new wave of rowsize error
