### ISSUE TITLE
PyPoE Exporter dat sql. Error while exporting on 21%.

### ISSUE THREAD

**Issue by ashcrok** [OmegaK2/PyPoE#24]
d:\workspace\poe-data>pypoe_exporter dat sql --url mysql://root:1234@127.0.0.1/pypoe
14:12:06 SQL init - Establishing DB connection
14:12:06 SQL init - Setting session sql_modes
14:12:06 d:\anaconda\lib\site-packages\sqlalchemy\engine\default.py:450:
Warning: (3135, "'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ERROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be merged with strict mode in a future release.")
14:12:07 SQL tables - Creating virtual tables from specification...
 21%|################8                                                               | 63/299 [00:00<00:00, 617.66it/s]
14:12:07 Traceback (most recent call last):
  File "d:\workspace\pypoe\PyPoE\cli\core.py", line 145, in run
    code = args.func(args)
  File "d:\workspace\pypoe\PyPoE\cli\exporter\dat\parsers\sql.py", line 268, in handle
    section = top_section['fields'][sub_field]
  File "d:\anaconda\lib\site-packages\configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'StatValues'

**Comment by OmegaK2** [comment]
The SQL exporter is discontinued. I'll close this issue when I remove it from the code

**Comment by ashcrok** [comment]
Any updates regarding the bug?

**Comment by eps1lon** [comment]
Well from his answer it's pretty obvious that this won't get a fix because it will be removed. 

I'm currently working on my own sql exporter written in js which will use the spec defined in this repo. I can notify you if I'm ready to publish if you wish.
