### ISSUE TITLE
Item png icons

### ISSUE THREAD

**Issue by ashcrok** [OmegaK2/PyPoE#32]
Hi, I am bit confused of how to retrieve the .png images of the items. Can you point me in the right direction to how to extract this information?

**Comment by OmegaK2** [comment]
Extract the .dds files from the ggpk with brotli installed and using the decompression either in the UI or as function in the CLI. 
You need to convert the .dds files to .png after that yourself with an application of your choice

**Comment by ashcrok** [comment]
I got into the pypoe-ui and installed brotli to get the Art folder tho an "Unsupported DDS Format" pops out and I can't find the .dds files locally. Are they stored somewhere or held in memory?

**Comment by OmegaK2** [comment]
Extract the file or the folder to the disk (select the file/folder -> right click -> extract), not all .dds files can be previewed inside PyPoE.

**Comment by ashcrok** [comment]
I successfully extracted the .dds files, but I tried out three .dds file converters to jpg/jpeg and to png but all of them would raise in error failing to convert (no reason given). Also downloaded a test .dds file from a git repository (not PoE related) and the converters work fine on it. May be something wrong with the extracting part on PyPoE side?

**Comment by OmegaK2** [comment]
Is "Uncompress DDS files after exporting them from the GGPK" checked under settings (Misc - settings)? Does it show "brotli is installed" in green?

**Comment by ashcrok** [comment]
Indeed, the "Uncompress DDS files after exporting them from the GGPK" wasn't checked. Thanks, now everything works fine :).
