### ISSUE TITLE
Unique items

### ISSUE THREAD

**Issue by ashcrok** [OmegaK2/PyPoE#33]
How can one retrieve the unique items from the game from the JSON file? Example: http://poedb.tw/us/unique.php?n=Last_Resort is an unique item from http://poedb.tw/us/item.php?n=Nailed+Fist but whatever I try, can't seem to find the correlation in the JSON file.

**Comment by OmegaK2** [comment]
Unique items are not in the game data. You can however try to search for the "componets" such as base item,  flavour text, item visual identity, mods etc since those are in the data.
