### ISSUE TITLE
Converting dat => csv => dat

### ISSUE THREAD

**Issue by Eliont** [OmegaK2/PyPoE#34]
Hello and good time of day. 
Can this toolset convert dat files to csv and then again to dat that can be loaded into Content.ggpk ?

**Comment by OmegaK2** [comment]
PyPoE doesn't support writing dat files or writing to the ggpk. The only case where I can see people trying to do that is trying to cheat which isn't something I want to support.

There is no direct support for exporting to csv, but you can do it yourself if you want.

**Comment by Eliont** [comment]
@OmegaK2  I founded en-ru translation group PoeLore when PoE don't have russian localization. We translate all dialogues, then garena stole one of our translators and our translation, renamed all characters and location and published it.  New acts released, some dialogues translated awfully wrong, some does not translated at all. We want to fix it, but dont have tool, PoeString not updated since "Sacrifice of the Vaal" and cant't find any other working solution.

**Comment by OmegaK2** [comment]
GGG doesn't allow using custom translations though. I would suggest trying to contact GGG (either support@grindinggear.com or Chris via chris@grindinggear.com) regarding your problems.

In any case, this no issue for PyPoE.
