### ISSUE TITLE
3.0.1 spec update

### ISSUE THREAD

**Issue by eps1lon** [OmegaK2/PyPoE#36]
Hey,

so I've been doing some work to figure out the new fields added with 3.0.1 and I was wondering if there already exists a platform to discuss the possible meaning of newly added or still unknown fields?

**Comment by zaafar** [comment]
a discord server maybe?

**Comment by OmegaK2** [comment]
If you want to use discord, I think using tool-dev channel on the poe discord would be a good place to go.
