### ISSUE TITLE
Nothing happens when i try to export .dat file

### ISSUE THREAD

**Issue by DemikGit** [OmegaK2/PyPoE#39]
Hello I'm trying to export .dat file using this command: 
D:\repositories\PyPoE> pypoe_exporter dat json D:\repositories\PyPoE\BaseItemTypes.json --files C:\Users\Zaly\Desktop\BaseItemTypes.dat
But nothing happens and the console just outputs this: 
usage: pypoe_exporter-script.py dat [-h] {json} ...
positional arguments:
{json} Export type
json Export to JSON

optional arguments:
-h, --help show this help message and exit"
What am I doing wrong and how to export .dat files?

**Comment by OmegaK2** [comment]
Which version of windows are you on? I think this may be some odd bug in python I've seen it happen to some people (arguments in the cli not getting parsed properly).

**Comment by DemikGit** [comment]
I use windows 7 sp1 x64 and python 3.4. How i can avoid this bug?

**Comment by flier268** [comment]
try this,
pypoe_exporter dat json D:\repositories\PyPoE\BaseItemTypes.json --files BaseItemTypes.dat
