### ISSUE TITLE
ImportError: No module named enum

### ISSUE THREAD

**Issue by tbarusseau** [OmegaK2/PyPoE#43]
Hello,

When starting up, I'm getting the `ImportError: No module named enum` error. `enum` wasn't added to Python until 3.4, so... My bet is that you're starting the program using `python` and not `python3`, which in my case is `python-2.7`. Note that the widely-accepted way of starting python is to call `python` only if your code is 2.7-compatible. In your case, it should be `python3`.

**Comment by OmegaK2** [comment]
What are you running exactly? python isn't directly invoked anywhere, the other scripts are created via setup.py
Perhaps you've installed it on python2 instead of python3.4+? Depending on how your system is setup  that would probably correspond to pip3 or pip3.4 during installation

**Comment by tbarusseau** [comment]
@OmegaK2 : I'm running the `pypoe_ui` program (through my terminal), after having done the full installation (`pip install -e .[full]`). Running the installed `/usr/local/bin/pypoe_ui` program with `python3.4` (explicitely) yields another error, but I think this is one step in the right direction :)

**Comment by OmegaK2** [comment]
Reinstall with 
> pip3.4 install -e .[full]

or 

> pip3 install -e .[full]

The latter might give errors when pip3 links to versions other then 3.4 due to lack of pyside support. 

I should probably update the quick setup guide.

**Comment by tbarusseau** [comment]
Ah, that makes sense. Thanks for clearing that up!
