### ISSUE TITLE
Maps.dat cannot be read from when raise_error_on_missing_relation=False is set

### ISSUE THREAD

**Issue by FWidm** [OmegaK2/PyPoE#44]
Hi! I've been trying to access the `.dat` files inside of the ggpk without extracting with your map example you've posted [here](https://www.reddit.com/r/pathofexiledev/comments/7jmpok/looking_for_atlas_maps_data/dr91u40/). 

You've mentioned that we have to set `raise_error_on_missing_relation=False`, which results in not being able to read Maps.dat at all for me. Does not matter whether you read from the `.dat` inside of the `.ggpk` or extracted ones.

Example:
```python
from PyPoE.poe.file.dat import RelationalReader
from PyPoE.poe.file.ggpk import GGPKFile

path = 'D:/Grinding Gear Games/Path of Exile/Content.ggpk'


def load_ggpk(ggpk_path):
    ggpk = GGPKFile()
    ggpk.read(ggpk_path)
    ggpk.directory_build()
    return ggpk


def create_relational_reader(ggpk):
    opt = {
        'use_dat_value': False,
        'auto_build_index': True,
    }
    return RelationalReader(path_or_ggpk=ggpk, read_options=opt, raise_error_on_missing_relation=False)


def parse(r: RelationalReader):
   #workaround around the raise error problem:
    try:
        maps = r['Maps.dat']
    except:
        print("Exception")
        maps = r['Maps.dat']
    print(r.__dict__)
    maps.build_index('Regular_WorldAreasKey')
    maps.build_index('Unique_WorldAreasKey')

    mapDictList = []

    ctr = 0
    for node in r['AtlasNode.dat']:
        ctr = ctr + 1
        map = maps.index['Regular_WorldAreasKey'].get(node['WorldAreasKey'].rowid)
        unique = False
        if map is None:
            map = maps.index['Unique_WorldAreasKey'].get(node['WorldAreasKey'].rowid)
            unique = True
        if map is None:
            print('Missing: %s' % node['WorldAreasKey']['Id'])
            continue
        # indexing creates a list unless unique is specified for the field in the specification
        map = map[0]


        mapDict = {}
        mapDict['Name'] = node['WorldAreasKey']['Name']
        mapDict['Tier'] = map['Tier']
        mapDict['Unique'] = unique
        mapDict['Coordinates'] = [node['X'], node['Y']]

        print(mapDict)

        mapDictList.append(mapDict)


print("Loading")
ggpk = load_ggpk(path)
print("Finish")
rr = create_relational_reader(ggpk)
parse(rr)

```

`raise error = False` out:
```
Missing: MapWorldsHydra
Missing: MapWorldsMinotaur
Missing: MapWorldsPhoenix
Missing: MapWorldsVaalTemple
Missing: MapWorldsShapersRealm
```

`raise error = True` out:
```
{'Unique': False, 'Name': 'Forge of the Phoenix', 'Tier': 16, 'Coordinates': [549.198974609375, 228.63699340820312]}
{'Unique': False, 'Name': 'Vaal Temple', 'Tier': 16, 'Coordinates': [472.4750061035156, 370.156005859375]}
{'Unique': False, 'Name': "The Shaper's Realm", 'Tier': 17, 'Coordinates': [499.8380126953125, 281.28900146484375]}

```

**Comment by OmegaK2** [comment]
I don't get the same output as you do when running this, it finds all the maps just fine with no missing ones. Is your GGPK & pypoe updated? What version of python you are on?

**Comment by OmegaK2** [comment]
Do you get missing for all keys? In that case remove .rowid from node['WorldAreasKey'].rowid

**Comment by FWidm** [comment]
Thanks, removing `.rowid` did the trick 👍 
Edit: When disabling raising errors, apparently the queueing of data changes a bit as well?

Just a quick and dirty test to retrieve the monster packs of a map:
This works fine with catching the error as i did but fails when i set raise error to false:

```python
        for key in map['MonsterPacksKeys']: 
            monster_pack_info['Id'] = monster_packs[key]['Id'] 
```

output:
```
TypeError: list indices must be integers, not DatRecord 
```

This is apparently, because key is of type `<class 'PyPoE.poe.file.dat.DatRecord'>` while it could be used as indice before. Would you say it is a problem to just catch the raised errors and load the file again afterwards as i did before? This seems to work fine for my use-case.

Thanks for your great work on the library btw.

**Comment by OmegaK2** [comment]
generally the point of the relational reader is to resolve those keys and replace the key (usually the rowid) with the actual value, when you catch the error and continue it doesn't complete this, leaving some keys as rowids or other values while the others up to that point would be replaced.

**Comment by FWidm** [comment]
Ah gotcha, everything is now in working order thanks to your explanation - I've had to manually get the `rowid` to retrieve some things but it works fine :).
