### ISSUE TITLE
Cannot view after extracting a DDS with Transparency

### ISSUE THREAD

**Issue by Vacuumvoid** [OmegaK2/PyPoE#45]
I was able to extract files and view them if they don't have a transparent background (e.g. AtlasBlank.dds AtlasCompletelyBlank.dds TouchOfGod.dds). However when I extract files with a transparent background, they can't be viewed (e.g. 2DArt_UIImages_InGame_7.dds 2DItems_Divination_Images_1.dds 2DArt_UIImages_InGame_CraftingWindow_1.dds), however I do have a preview in GGPK of those files. Is there a problem with the extraction or am I not using the tools to view them?

**Comment by OmegaK2** [comment]
Try something like IrfanView and let me know if it works.

**Comment by Vacuumvoid** [comment]
Just tried IrfanView and it didn't seem to work. IrfanView wasn't even able to open the other DDS files that I was able to open before.

**Comment by Vacuumvoid** [comment]
Nevermind, it worked but when I exported as PNG, it doesn't preserve the transparency.

EDIT:
Did some digging, I don't think it is the transparency that messes the files up, I think it might be something else. I was able to extract and view ShapersFlask.dds (and other files alike) with normal DDS viewing softwares, but when it comes to the files I have described the very top of the issue and div cards (2DItems_Divination_Images_1.dds), they seem to not work.

**Comment by OmegaK2** [comment]
Do you have brotli installed and "Uncompress DDS files after exporting them from the GGPK" checked?

**Comment by Vacuumvoid** [comment]
Yep, otherwise I wouldn't be able to view and extract AtlasBlank.dds etc. in the first place. Are you having the same issue or am I the only one?

**Comment by OmegaK2** [comment]
The only time I can replicate "not being able to view" files is by unchecking brotli. The uncompressed, extracted 2DItems_Divination_Images_1.dds should show as "556 KB (569.872 Bytes)", can you confirm that?

**Comment by Vacuumvoid** [comment]
569,872 Bytes. Yep. I can view these files in IrfanView but it has a transparency issue when I try to export it as another format.
EDIT:
Are there other tools I could use?

**Comment by OmegaK2** [comment]
I think this is just an issue with converting using other tools then not necessarily within PyPoE. It looks like it renders right so long a black background is used.

**Comment by Vacuumvoid** [comment]
Why does a problem like this exist? I use Paint.Net and PhotoShop for example, they are able to open files such as AtlasBlank.dds AtlasCompletelyBlank.dds just fine but when it comes to these 2DItems_Divination_Images_1.dds 2DArt_UIImages_Login_4K_2.dds files, they refuse to open. What is causing this issue, is it a bug?

**Comment by lucifering** [comment]
I try to use Brotli.NET to decode the same, black background.
DXT3 is ok ,DXT4 no(black background).

Edit: black background is  fine,the software does not support the preview of the format.(IrfanView and Ps)

https://imgur.com/a/VwKAx

**Comment by zaafar** [comment]
VS2017 can also read a dds file...
