### ISSUE TITLE
Skill-gem types totally wrong

### ISSUE THREAD

**Issue by tkozybski** [OmegaK2/PyPoE#52]
Looks like 3.2 broke the gem's types, for example look at tectonic slam: http://poedb.tw/us/gem.php?n=Tectonic+Slam http://poedb.tw/us/gem.php?n=Incinerate
Last time I checked Incinerate was not a curse.

**Comment by OmegaK2** [comment]
And what is the issue with pypoe exactly?

**Comment by tkozybski** [comment]
I thought PyPoE is poedb's base, it's not? :o Well i'll close the issue then.
