### ISSUE TITLE
Default export of .dat to JSON doesn't include all data?

### ISSUE THREAD

**Issue by lutel** [OmegaK2/PyPoE#61]
Hi,

I did export with "pypoe_exporter dat json out.json" - but the json file apparently doesn't include all data, for example I can't find a string "When You Kill An Ignited" in it (part of Abberath's Hooves description). Do I have to set in options some additional .dat files to export to see all the data for uniques? I hope the data is present in files as I see RePoE has this data and as I understand it is a wrapper on PyPoe...

**Comment by eps1lon** [comment]
The descriptions are contained within `MetaData/StatDescriptions`. 

Uniques are not contained within the dat files. Some uniques have mods that contain a hint to their unique in their id e.g. `SomeModUniqueBootStrDex6`.

**Comment by OmegaK2** [comment]
The exporter just exports the raw data from the dat files. There are further wrappers/functionality to work with the translations (which is the text you talk about). As eps1lon said there is no association for the unique data in the files, it's scattered all around.
I'm closing this one as it isn't really an issue with the exporter.
