### ISSUE TITLE
.dds Files export header invalid (PoE 3.4)

### ISSUE THREAD

**Issue by aleskozina** [OmegaK2/PyPoE#73]
Hi Dude!

First of all, great work!

Im planing to create my own tool for PoE and for this i'm getting familiar with PyPoE. Im a web developer but i'm struggling with python because i got no experience in it and thats why i'm creating this issue to ask you!

I have problems with the .dds files/pictures.
What i already know and did:
- They are compressed with brotli, have this 4(if i remember correctly) bytes of metadata which do not belong originally to dds-files
- I have installed the latest brotli (1.0.7)
- The images are displayed correctly on your GUI
- set settings to decompress after export in GUI

After i export your .dds files and want to convert them to png/jpg with imagemagick (convert function) i always get an error message that the header is not correct.

There are to ways to export in your GUI: 
- rightlick on the file in the filestructure of your GUI
- Export button in the menu/toolbar

My Environment:
- latest Python (3.7)
- latest brotli (1.0.7)
- Win 10
- Path of Exile Content.ggpk: 3.4
- missing something?

Can you verify that under these circumstances your export is still working?
Do i need to change something or have i forgot something?

As i told, im a developer and i dug alot into your code. Tried to intercept and save the files manually after decompressing with brotli but in all cases i could not manage to export a valid dds file.

Would very appreciate your feedback!

Kind Regards
Ales

**Comment by OmegaK2** [comment]
Can you test something like Art/2DItems/Amulets/Amulet10.dds and see whether it is ~32kb after unpacking form ggpk?

**Comment by aleskozina** [comment]
Simple solution: Uncheck and check the decompress-check in settings of the GUI.
