### ISSUE TITLE
ItemClassesKey and craftingbenchoptions

### ISSUE THREAD

**Issue by eps1lon** [OmegaK2/PyPoE#9]
Some keys are set to `0`. I cant see a pattern since some keys are still valid while others basically got removed.

Dont know if this is a) a problem with the ggpk viewer b) a conscious decision by the devs to obfuscate more or c) a preview of upcoming changes to craftingbenches (though nothing was mentioned in the patch nodes)

I first noticed this in 2.1.2d. It's still the same in 2.1.2e.

**Comment by OmegaK2** [comment]
It's just a mistake with the data type for that column. It should be ref|list|ulong instead of ref|list|uint
I'll fix that with an update when I also update the specification for 2.2

**Comment by eps1lon** [comment]
Nice, thanks!
