### ISSUE TITLE
stable.py

### ISSUE THREAD

**Issue by aianlinb** [OmegaK2/PyPoE#99]
PyPoE/PyPoE/poe/file/specification/data/stable.py

'PCBangRewardMicros.dat': File(
        fields=OrderedDict((
            ('Unknown0', Field(
                name='Unknown0',
                type='ref|string',
            )),
            ('Unknown1', Field(
                name='Unknown1',
                type='int',
            )),
            ('Unknown2', Field(
                name='Unknown2',
                type='int',
            )),
        )),
    ),
	
Should Be

'PCBangRewardMicros.dat': File(
        fields=OrderedDict((
            ('BaseItemTypesKey', Field(
                name='BaseItemTypesKey',
                type='ulong',
            )),
            ('Unknown1', Field(
                name='Unknown1',
                type='int',
            )),
        )),
    ),

**Comment by zaafar** [comment]
Ref: https://github.com/MuxaJIbI4/libggpk/commit/6336950fcbb0320f88b0ab860e2e43fc1bf7f3d9 ;)

**Comment by aianlinb** [comment]
> Ref: [MuxaJIbI4/libggpk@6336950](https://github.com/MuxaJIbI4/libggpk/commit/6336950fcbb0320f88b0ab860e2e43fc1bf7f3d9) ;)

Ref: https://github.com/MuxaJIbI4/libggpk/issues/20 :)
